events {}
http {
  server {
    listen 80;                        # Listen on port 80 for HTTP
    location / {                      # Match all request URIs
      proxy_pass         http://python-api:8000;    # Forward requests to the “api” container on port 8000
      proxy_set_header   Host $host;                # Preserve the original Host header
      proxy_set_header   X-Real-IP $remote_addr;    # Pass along the client’s IP address
    }
  }
}